[versions]
agp = "8.6.0"
coilCompose = "2.6.0"
kotlin = "2.1.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
composeBom = "2025.06.00"
gmsVersion = "4.4.2"
bomVersion = "33.15.0"

navigationCompose = "2.9.0"
serializationVersion = "2.1.0"
serializationKotlin = "1.7.3"

#dagger-hilt
hiltAndroid = "2.51.1"
hiltNavCompose = "1.2.0"
kspPlugin = "2.1.0-1.0.29"
hiltPlugin = "2.50"


[libraries]
#coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "bomVersion" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx"}
firebase-storage = { group = "com.google.firebase", name = "firebase-storage-ktx"}
firebase-auth = { module = "com.google.firebase:firebase-auth" }


kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationKotlin" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

android-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
android-hilt-compliler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }

hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavCompose" }
hilt-navigation-compose-compiler = {module = "androidx.hilt:hilt-compiler", version.ref = "hiltNavCompose" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsVersion" }

plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationVersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }

